/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RouteFilterIdRouteImport } from './routes/route.$filterId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteFilterIdRoute = RouteFilterIdRouteImport.update({
  id: '/route/$filterId',
  path: '/route/$filterId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/route/$filterId': typeof RouteFilterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/route/$filterId': typeof RouteFilterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/route/$filterId': typeof RouteFilterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/route/$filterId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/route/$filterId'
  id: '__root__' | '/' | '/route/$filterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RouteFilterIdRoute: typeof RouteFilterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route/$filterId': {
      id: '/route/$filterId'
      path: '/route/$filterId'
      fullPath: '/route/$filterId'
      preLoaderRoute: typeof RouteFilterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RouteFilterIdRoute: RouteFilterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
